POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "VS Code REST Client testing an HTTP POST",
    "number": 12345
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "VS Code REST Client testing an HTTP POST",
    "number": null
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": null,
    "number": 12345
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ryan Bennett",
    "number": 6666666666666
}
###
GET http://localhost:3001/api/persons